# .github/workflows/ci-cd.yml (fragmento)
jobs:
  ci:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Show Node & npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies (prefer ci)
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci --no-audit --no-fund
          else
            echo "No package-lock.json found; falling back to npm install"
            npm install --no-audit --no-fund
          fi

      - name: Lint
        run: npm run lint

      - name: Test (with coverage)
        run: npm test

      - name: Print npm debug logs on failure
        if: failure()
        run: |
          echo "Dumping npm logs..."
          find ~/.npm/_logs -type f -name '*-debug-*.log' -print -exec sed -n '1,200p' {} \;
